### ISSUE TITLE
Some of these need to be dragged to the bookmarks bar, but you can't drag them there.

### ISSUE THREAD

**Issue by Tacogamerman** [Blobby3892/Dragon-Hub#1]
For some of the bookmarklets, they only work if you drag them to the bookmarks bar. However, dragon hub does not allow you to drag them.

Also about:blank unblocker only works if you get it to request a url and redirect you to it, or else it will just about:blank the block screen.

**Comment by Blobby3892** [comment]
The new fully reworked gui will fix this issue
